"""Typed annotation loading, validation, and statistics.

Public API of the ``annotations`` subpackage: the loader
(``AnnotationDatasetLoader``), the typed internal representation
(``AnnotationRecord``, ``AnnotatedQuestion``, ``Interpretation``,
``AnnotationDataset``), and read-only statistics
(``compute_stats`` / ``AnnotationDatasetStats``). The annotation-preparation
tooling (screening manifest, workspace construction, provenance sidecar, and
the batch QC/freeze checks) also lives here.
"""
from .batch import (
    ANSWERABILITY_CODES,
    BATCH1_TARGET,
    BATCH_ID,
    EVALUABLE_CODES,
    MAX_SPANS_PER_FAMILY,
    METADATA_CLOSABLE_CODES,
    NON_EVALUABLE_CODES,
    PERSISTENT_SPAN_TARGETS,
    PROTOCOL_VERSION,
    STRATUM_TARGETS,
    THIRD_LABEL_FRACTION,
    build_screening_manifest,
    select_third_label_sample,
)
from .errors import (
    AnnotationLoadError,
    AnnotationPrepError,
    AnnotationValidationError,
)
from .human import (
    HUMAN_GOLD_VERSION,
    IAA_NOTE,
    build_human_provenance,
    build_human_record,
    build_human_task_list,
    freeze_human_gold,
    human_task_payload,
    load_human_task_list,
    record_to_flat_dict,
    regenerate_human_records,
    validate_human_record,
    validate_human_root,
    write_human_provenance,
    write_human_task_list,
)
from .loader import AnnotationDatasetLoader
from .models import (
    AnnotatedQuestion,
    AnnotationDataset,
    AnnotationRecord,
    AnnotationSpan,
    Answerability,
    AnswerabilityLabel,
    AssumptionRisk,
    Interpretation,
    ResolutionChannel,
)
from .provenance import (
    ENRICHMENT_TOKEN_DERIVATION,
    PLACEHOLDER,
    PROVENANCE_VERSION,
    Adjudication,
    EnrichmentSnapshot,
    ProvenanceSidecar,
    build_provenance_skeleton,
    derive_enrichment_token,
    load_sidecar,
    write_sidecar,
)
from .qc import batch_report, freeze_batch, load_batch, validate_batch, write_lock
from .stats import AnnotationDatasetStats, compute_stats
from .workspace import (
    BATCH_INPUT_VERSION,
    blank_template,
    build_annotation_workspace,
    build_batch_input,
    schema_to_annotator_view,
)

__all__ = [
    "ANSWERABILITY_CODES",
    "Adjudication",
    "AnnotatedQuestion",
    "AnnotationDataset",
    "AnnotationDatasetLoader",
    "AnnotationDatasetStats",
    "AnnotationLoadError",
    "AnnotationPrepError",
    "AnnotationRecord",
    "AnnotationSpan",
    "AnnotationValidationError",
    "Answerability",
    "AnswerabilityLabel",
    "AssumptionRisk",
    "BATCH1_TARGET",
    "BATCH_ID",
    "BATCH_INPUT_VERSION",
    "ENRICHMENT_TOKEN_DERIVATION",
    "EVALUABLE_CODES",
    "EnrichmentSnapshot",
    "HUMAN_GOLD_VERSION",
    "IAA_NOTE",
    "Interpretation",
    "MAX_SPANS_PER_FAMILY",
    "METADATA_CLOSABLE_CODES",
    "NON_EVALUABLE_CODES",
    "PERSISTENT_SPAN_TARGETS",
    "PLACEHOLDER",
    "PROTOCOL_VERSION",
    "PROVENANCE_VERSION",
    "ProvenanceSidecar",
    "ResolutionChannel",
    "STRATUM_TARGETS",
    "THIRD_LABEL_FRACTION",
    "batch_report",
    "blank_template",
    "build_annotation_workspace",
    "build_batch_input",
    "build_human_provenance",
    "build_human_record",
    "build_human_task_list",
    "build_provenance_skeleton",
    "build_screening_manifest",
    "compute_stats",
    "derive_enrichment_token",
    "freeze_batch",
    "freeze_human_gold",
    "human_task_payload",
    "load_batch",
    "load_human_task_list",
    "load_sidecar",
    "record_to_flat_dict",
    "regenerate_human_records",
    "schema_to_annotator_view",
    "select_third_label_sample",
    "validate_batch",
    "validate_human_record",
    "validate_human_root",
    "write_human_provenance",
    "write_human_task_list",
    "write_lock",
    "write_sidecar",
]
