"""Batch-1 construction design and deterministic screening tooling (docs/19 §3-§4).

The batch itself cannot be constructed mechanically: stratum/family assignment
is a human screening decision (docs/13 §4, §8; docs/19 §5.3), and the
metadata-closable stratum must cite a specific enrichment entry that does not
yet exist. This module therefore ships the *frozen design constants* (docs/19
§4), the deterministic gold-free **screening manifest** template a human team
uses to make the selection, and the deterministic 10% third-label sample
selector (docs/13 §7).

No ambiguity label is ever inferred here: candidate signals are screening
hints only (docs/19 §5.1) and no gold field is read. The third-label selector
requires a pre-registered seed (docs/13 §7 fixes only the 10% fraction); until
the seed is officially fixed the selector must not be applied to a real batch
(docs/19 §11), so no sample is generated by this slice.
"""
from __future__ import annotations

import random
from collections.abc import Mapping, Sequence
from typing import Any

from eaa.ambiguity_resolution.candidates import CandidatePool
from eaa.core.contracts.schema import DatabaseSchema

BATCH_ID = "batch-1"

#: docs/19 §4.1 — target size for the first batch.
BATCH1_TARGET = 60

#: docs/19 §4.1 — per-stratum question targets.
STRATUM_TARGETS: dict[str, int] = {
    "metadata_closable": 15,
    "persistent_ambiguity": 30,
    "unambiguous": 15,
}

#: docs/19 §4.2 — span allocation for the persistent-ambiguity stratum.
PERSISTENT_SPAN_TARGETS: dict[str, int] = {
    "S": 5,
    "R": 4,
    "C": 8,
    "T": 5,
    "K": 4,
    "I": 4,
    "L+V (metadata-present-but-not-decisive)": 3,
}

#: docs/19 §4.3 — codes eligible for the metadata-closable stratum.
METADATA_CLOSABLE_CODES: tuple[str, ...] = ("L2", "R1", "V1", "V2", "V3", "T2", "K2")

#: docs/19 §4.2 — cap on spans within one ambiguity family.
MAX_SPANS_PER_FAMILY = 8

#: Paper 1 evaluable span codes (docs/19 §2, docs/15 §3.4).
EVALUABLE_CODES: frozenset[str] = frozenset(
    {
        "L2",
        "S1",
        "S2",
        "R1",
        "R2",
        "V1",
        "V2",
        "V3",
        "C1",
        "C2",
        "C3",
        "T1",
        "T2",
        "K1",
        "K2",
        "I2",
        "I3",
    }
)

#: Declared coverage limitations (docs/19 §2) — never valid span codes.
NON_EVALUABLE_CODES: frozenset[str] = frozenset({"L1", "C4", "I1"})

#: Unanswerability codes — valid only as ``answerability`` labels, never spans.
ANSWERABILITY_CODES: frozenset[str] = frozenset({"U1", "U2", "U3", "U4"})

#: docs/13 §7 / docs/19 §8 — third-label sample fraction.
THIRD_LABEL_FRACTION = 0.10

#: The annotation schema both the labels and the provenance sidecar cite.
PROTOCOL_VERSION = "annotation-schema-v1"

_METHOD_NOTE = (
    "selection is a human screening decision; candidate signals are "
    "screening hints only and no ambiguity label is inferred here"
)


def build_screening_manifest(
    pool: CandidatePool,
    schemas: Mapping[str, DatabaseSchema],
    *,
    batch_id: str = BATCH_ID,
) -> dict[str, Any]:
    """Build the deterministic, gold-free batch-1 screening manifest.

    Parameters
    ----------
    pool:
        The candidate pool (questions plus fired signals; gold is never read).
    schemas:
        Resolved ``DatabaseSchema`` per database id, used only to mark which
        candidates have a schema available for the annotator.
    batch_id:
        Batch identifier recorded in the manifest.

    Returns
    -------
    dict
        The manifest: batch id, protocol versions, frozen stratum/family
        targets, pool summary, and one row per candidate with selection left
        open to human screening.
    """
    rows: list[dict[str, Any]] = []
    for record in pool.candidates:
        rows.append(
            {
                "question_id": record.question_id,
                "database_id": record.database_id,
                "question": record.question,
                "signals": [hit.signal for hit in record.signals],
                "schema_available": record.database_id in schemas,
                "stratum": None,
                "selection_status": "unselected",
                "selection_reason": None,
            }
        )
    return {
        "batch_id": batch_id,
        "schema_version": PROTOCOL_VERSION,
        "provenance_version": "provenance-v1",
        "stratum_targets": STRATUM_TARGETS,
        "persistent_family_span_targets": PERSISTENT_SPAN_TARGETS,
        "metadata_closable_codes": list(METADATA_CLOSABLE_CODES),
        "max_spans_per_family": MAX_SPANS_PER_FAMILY,
        "signals_are_screening_hints_not_labels": True,
        "gold_inference": "never",
        "selection_rule": _METHOD_NOTE,
        "metadata_closable_blocked_reason": (
            "no legitimate enrichment.json exists; every metadata-closable item "
            "must cite the specific enrichment entry that pins its reading "
            "(docs/19 §4.3)"
        ),
        "pool": {
            "total": len(pool.candidates),
            "by_database": pool.counts_by_database(),
        },
        "candidates": rows,
    }


def select_third_label_sample(
    question_ids: Sequence[str],
    *,
    seed: int | str,
    fraction: float = THIRD_LABEL_FRACTION,
) -> tuple[str, ...]:
    """Deterministically select the pre-registered 10% third-label sample.

    Parameters
    ----------
    question_ids:
        The batch question ids to sample from.
    seed:
        The officially pre-registered seed. **Not chosen by this slice**: the
        protocol fixes only the fraction (docs/13 §7), so ``seed`` must come
        from the researcher decision recorded in the experiment record.
    fraction:
        Third-label fraction (default 10%).

    Returns
    -------
    tuple
        The sorted sample of ``question_id`` values; identical for identical
        inputs, so the selection is reproducible once the seed is fixed.

    Raises
    ------
    ValueError:
        If ``fraction`` is not in (0, 1).
    """
    if not 0.0 < fraction < 1.0:
        raise ValueError(f"fraction must be in (0, 1), got {fraction!r}")
    ids = sorted(set(question_ids))
    if not ids:
        return ()
    size = max(1, round(len(ids) * fraction))
    rng = random.Random(seed)  # noqa: S311 - reproducible sampling, not security
    return tuple(sorted(rng.sample(ids, size)))


__all__ = [
    "ANSWERABILITY_CODES",
    "BATCH1_TARGET",
    "BATCH_ID",
    "EVALUABLE_CODES",
    "MAX_SPANS_PER_FAMILY",
    "METADATA_CLOSABLE_CODES",
    "NON_EVALUABLE_CODES",
    "PERSISTENT_SPAN_TARGETS",
    "PROTOCOL_VERSION",
    "STRATUM_TARGETS",
    "THIRD_LABEL_FRACTION",
    "build_screening_manifest",
    "select_third_label_sample",
]
